version: '3.8'

services:
  # Java Web Application với Tomcat
  webapp:
    build: .
    container_name: ta_webapp
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      # Mount logs để có thể xem logs từ host
      - ./logs:/opt/tomcat/logs
      # Mount config nếu cần customize
      - ./config:/opt/tomcat/conf
    networks:
      - ta_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: ta_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - webapp
    networks:
      - ta_network
    restart: unless-stopped
    profiles:
      - with-nginx

  # MySQL Database (optional)
  mysql:
    image: mysql:8.0
    container_name: ta_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ta_webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: webapp123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    networks:
      - ta_network
    restart: unless-stopped
    profiles:
      - with-database

  # Redis Cache (optional)
  redis:
    image: redis:alpine
    container_name: ta_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ta_network
    restart: unless-stopped
    profiles:
      - with-cache

networks:
  ta_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
